image: gradle:jdk17

variables:
  PROJECT_NAME: "${CI_PROJECT_NAME}"
  JFROG_BASE_URL: "${JFROG_BASE_URL}"
  JFROG_REPOSITORY: "${JFROG_REPOSITORY}"
  JFROG_PUSH_URL: "${JFROG_BASE_URL}/${JFROG_REPOSITORY}"
  ARTIFACT_PATH: "build/libs/${CI_PROJECT_NAME}*.jar"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - ./gradlew build -x test
    - JAR_FILE=$(ls build/libs/*.jar)
    - curl -u "$JFROG_USERNAME:$JFROG_PASSWORD" -T "$JAR_FILE" $JFROG_PUSH_URL
  artifacts:
    paths:
      - build/libs/*.jar   # keep build artifact for deployment

deploy:
  stage: deploy
  needs: ["build"]
  before_script:
    - apt-get update -qq && apt-get install -y sshpass
  script:
    - sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
      cd $PROJECT_NAME;
      git pull origin main;
      echo 'Stopping existing SimpleServer process...';
      pid=\$(ps aux | grep SimpleServer | grep -v grep | awk '{print \$2}');
      if [ -n \"\$pid\" ]; then
        kill -9 \$pid && echo 'Process stopped.';
      else
        echo 'No existing process found.';
      fi && \
      nohup ./gradlew bootRun > log.txt 2>&1 & disown
      "
    - echo "Deploying to VPS..."
  only:
    - main
