image: maven:3.8.3-openjdk-17

stages:
  - build
  - deploy

build:
    stage: build
    script:
      - echo "Building the project..."
      - mvn clean install
deploy:
    stage: deploy
    script:
      - echo "Deploying the project..."
    only:
        - main