image: gradle:jdk17

variables:
    PROJECT_NAME: "${CI_PROJECT_NAME}"

stages:
  - build
  - deploy

build:
    stage: build
    script:
      - echo "Building the project..."
      - ./gradlew build -x test
deploy:
    stage: deploy
    script:
      - echo $VPS_PASSWORD | ssh $VPS_USER@$VPS_IP "
        cd $PROJECT_NAME
        git pull origin main
        nohup ./gradlew bootRun > log.txt 2>&1 &
        "
    only:
        - main