version: '3.8'

services:
  apicurio-registry:
    image: apicurio/apicurio-registry:latest-snapshot
    ports:
      - "9081:8080"
    environment:
      REGISTRY_LOG_LEVEL: INFO
      QUARKUS_PROFILE: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    stdin_open: true
    tty: true

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    command: ["--query.max-clock-skew-adjustment=5s"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning