postgres.host=localhost
postgres.port=5432
postgres.database=freedraw
postgres.user=postgres
postgres.password=postgres
postgres.connection.pool.size=10
postgres.connection.minimum.idle.size=2
postgres.connection.timeout=3000
